[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pcpm"
version = "0.33.0"
description = "potato c package menager"
dependencies = []
authors = [{name = "sch", email="sch@potatom.ru"}]

[project.scripts]
pcpm = "pcpm.__main__:main"